### NUMPY ARRAY

Array is the collection of homogenous elements.  
The data stored can be int or float or string.


#### Important : numpy documentation
https://numpy.org/doc/stable/reference/arrays.ndarray.html

In [1]:
#! pip install numpy==1.20.0     Install numpy

In [2]:
import numpy as np

In [3]:
np.__version__    # to check the version of numpy

'1.20.0'

In [4]:
# defining the list

lst = [1,2,3,4]
type(lst)

list

In [5]:
# typecasting the list to array

b = np.array(lst)
print(b)
type(b)

[1 2 3 4]


numpy.ndarray

In [6]:
# shape of the array
b.shape

(4,)

### 2D array

In [7]:
# creating a 2-d array

x = [[1,2,3,4],[4,5,6,7],[7,8,9,10]]
x

[[1, 2, 3, 4], [4, 5, 6, 7], [7, 8, 9, 10]]

In [8]:
y = np.array(x)
y

array([[ 1,  2,  3,  4],
       [ 4,  5,  6,  7],
       [ 7,  8,  9, 10]])

In [9]:
y.shape   # (rows count, columns count)

(3, 4)

In [10]:
np.array((1,2,3,4,5))

array([1, 2, 3, 4, 5])

In [11]:
np.array("ineuron")

array('ineuron', dtype='<U7')

In [12]:
# y has 12 elements. Based on this count we can reshape.
# the reshape product has to be 12 only

y.reshape(2,6)

array([[ 1,  2,  3,  4,  4,  5],
       [ 6,  7,  7,  8,  9, 10]])

In [13]:
y.reshape(2,8)

ValueError: cannot reshape array of size 12 into shape (2,8)

In [14]:
# how to convert a 2d array to 3d array
# we can find the dimension by counting the number of 
# opening or closing sq brackets.

y.reshape(1,2,6)  # one 2X6 matrix

array([[[ 1,  2,  3,  4,  4,  5],
        [ 6,  7,  7,  8,  9, 10]]])

In [15]:
y.reshape(4,3,1)   # four 3X1 matrix

array([[[ 1],
        [ 2],
        [ 3]],

       [[ 4],
        [ 4],
        [ 5]],

       [[ 6],
        [ 7],
        [ 7]],

       [[ 8],
        [ 9],
        [10]]])

In [16]:
b.shape

(4,)

In [17]:
b.reshape(1,4).shape

(1, 4)

In [18]:
lst = [1.0, 2.0,1,"s"]
lstnp = np.array(lst)
lstnp

# see datatype is <U32 - see the doc link in the top markdown cell.

array(['1.0', '2.0', '1', 's'], dtype='<U32')

In [19]:
# one more method to create n dimension array

np.array([[1,2,3],[4,5,6]],ndmin = 5).shape

(1, 1, 1, 2, 3)

In [20]:
# np.array()   #shift+tab for more attributes

In [21]:
# change the d type of the array

In [22]:
 np.array([1,2,3], dtype = 'complex')

array([1.+0.j, 2.+0.j, 3.+0.j])

In [23]:
 np.array([1,2,3], dtype = 'float')

array([1., 2., 3.])

In [24]:
 np.array([1,2,3], dtype = np.int32)

array([1, 2, 3])

In [25]:
 np.array([1,2,3], dtype = np.complex_)

array([1.+0.j, 2.+0.j, 3.+0.j])

In [26]:
x=np.array([(1,2),(3,4)], dtype = [('a','<i2'),('b','<i8')])
x

array([(1, 2), (3, 4)], dtype=[('a', '<i2'), ('b', '<i8')])

In [27]:
print(type(x[0][0]))
print(type(x[0][1]))
print(type(x[1][0]))
print(type(x[1][1]))

<class 'numpy.int16'>
<class 'numpy.int64'>
<class 'numpy.int16'>
<class 'numpy.int64'>


### indexing in ndarray

In [28]:
lst = [1,2,3,4,5,6,7,8,9]
lst[1:3]

# indexing in list
#      list_name[lower limit: Upper limit(excluded)] 

[2, 3]

In [29]:
y

array([[ 1,  2,  3,  4],
       [ 4,  5,  6,  7],
       [ 7,  8,  9, 10]])

In [30]:
print(y[0][0])
print(y[0:2,0:2])

# indexing in ndarray

#   arr_name[rownum][colnum]  ---for selecting single element

#                      --- for selectin a range
#   arr_name[row_lower_limit:row_upper_limit(ex) , col_lower_limit:col_upper_limit(ex)]

1
[[1 2]
 [4 5]]


In [31]:
y[1:3,0:2]

array([[4, 5],
       [7, 8]])

In [32]:
# in y select 4 7  , 7 10
y

array([[ 1,  2,  3,  4],
       [ 4,  5,  6,  7],
       [ 7,  8,  9, 10]])

In [33]:
# selecting the diff rows and cols

y[1:,[0,3]]

array([[ 4,  7],
       [ 7, 10]])

In [34]:
# get 1,4,7,10


y[[0,2]][:,[0,3]]

array([[ 1,  4],
       [ 7, 10]])

In [35]:
np.ndarray()

TypeError: ndarray() missing required argument 'shape' (pos 1)

### Matrix is a subclass under numpy

np.matrix()  
np.mat()  
np.asmatrix()

By def'n matrix is a 2d array. Matrix has rows and columns of data.

In [36]:
x = [1,2,3,4]
print(np.mat(x))
print(type(x))

[[1 2 3 4]]
<class 'list'>


In [37]:
issubclass(np.matrix,np.ndarray)

True

In [38]:
# typecasting between matrix and ndarray

np.mat(np.array(x))

matrix([[1, 2, 3, 4]])

In [39]:
np.mat(np.array(x)).shape

(1, 4)

In [40]:
np.mat('1 2; 3 4; 4 5')

matrix([[1, 2],
        [3, 4],
        [4, 5]])

In [41]:
np.mat('1 2 5; 3 4 8; 4 5 9')

matrix([[1, 2, 5],
        [3, 4, 8],
        [4, 5, 9]])

In [42]:
x = np.array([[1, 2], [3, 4]])

m = np.asmatrix(x)
m

matrix([[1, 2],
        [3, 4]])

In [43]:
np.matrix()  -   creates the copy
np.mat()     -   no copy - directs to memory loaction
np.asmatrix()-   

SyntaxError: invalid syntax (<ipython-input-43-2d4c95ba6cf4>, line 1)

In [44]:
x = np.mat('1 2 ; 3 4')  # shallow copy
x

matrix([[1, 2],
        [3, 4]])

In [45]:
m = np.matrix(x)   # deep copy   copy = True
m

matrix([[1, 2],
        [3, 4]])

In [46]:
n = np.asmatrix(x)  # shallow copy
n

matrix([[1, 2],
        [3, 4]])

In [47]:
x[0,0] = 22

In [48]:
print("X is ", x)
print("m is ", m)
print("n is ", n)

X is  [[22  2]
 [ 3  4]]
m is  [[1 2]
 [3 4]]
n is  [[22  2]
 [ 3  4]]


### np.asarray

In [49]:
arr1 = np.array([1,2,3,45])

In [50]:
arr2 = np.asarray([1,2,3,45])

In [51]:
arr1 == arr2

array([ True,  True,  True,  True])

In [52]:
arr1 is arr2   # is checks the memory location

False

In [53]:
a = [1,2]
b = a.copy()      # deep copy - copy array to new memory location
a is b            # diff memory loaction for saving

False

In [54]:
a = [1,2]
b = a.copy()
b[0]=855
print(a)
print(b)
a is b

[1, 2]
[855, 2]


False

In [55]:
a = [1,2]
b = a     # shallow copy - same momory location for 2 variables.
a is b    # same memory location for saving

True

In [56]:
b[0]=855
print(a)
print(b)
a is b

[855, 2]
[855, 2]


True

In [57]:
a = 10
b = 10
a is b

True

In [58]:
a = 256
b = 256
a is b

True

In [59]:
a = 257
b = 257
a is b

False

#### np.array()  
#### np.asarray()  
#### np.asanyarray()

see below link for difference - 
https://stackoverflow.com/questions/14415741/what-is-the-difference-between-numpys-array-and-asarray-functions#:~:text=Most%20of%20the%20other%20functions%20are%20thin%20wrappers%20around%20array,False%20%2C%20subok%3DTrue%20).

In [69]:
a = [1,2,3,4,5]
np.array(a)

array([1, 2, 3, 4, 5])

In [73]:
n1 = np.array(a)
n1
print(n1)
type(n1)

[1 2 3 4 5]


numpy.ndarray

In [62]:
n2 = np.asarray(a)
print(n2)
type(n2)

[1 2 3 4 5]


numpy.ndarray

In [63]:
n3 = np.asanyarray(a)
print(n3)
type(n3)

[1 2 3 4 5]


numpy.ndarray

In [65]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [74]:
b = np.array(a)    # deep copy of a
b is a

# a is an array. np.array() press shift+tab - copy = True is default
# so this function creates an copy of array a at diff location

False

In [75]:
c = np.asarray(a)    # shallow copy of a 
c is a

# a is an array. np.asarray() creates array c with momory location same as a.
# copy from memory location is what we can say.

False

In [76]:
print(a,b,c)

[1, 2, 3, 4, 5] [1 2 3 4 5] [1 2 3 4 5]


#### np.fromfunction()

In [77]:
np.fromfunction(lambda l, m: l == m, (3,3), dtype=int)

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [78]:
np.fromfunction(lambda l, m: l * m, (3,3), dtype=int)

array([[0, 0, 0],
       [0, 1, 2],
       [0, 2, 4]])

### np.fromiter( )  & np.fromstring( )

In [112]:
a = (x*x for x in range(5,200,5))
a

<generator object <genexpr> at 0x000001A6F5996548>

In [113]:
np.fromiter(a, float, count=5)

array([ 25., 100., 225., 400., 625.])

In [124]:
np.fromstring("1 2 3 4 5 ", int, count = 5, sep =" ")

array([1, 2, 3, 4, 5])

In [126]:
np.fromstring("1,2,3,4,5,6,7,8,9", int, count = -1, sep =",")

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

### Create records from array

In [144]:
x0=np.array(["id", "name", "college"])
x1=np.array([1,"virat", "ineuron"])
x2=np.array([2,"rohit","ineuron02"])
x3=np.array([3,"rahul", "ineuron03"])

In [145]:
r = np.core.records.fromarrays([x0,x1,x2,x3],titles = "the max")

In [146]:
r

rec.array([('id', '1', '2', '3'), ('name', 'virat', 'rohit', 'rahul'),
           ('college', 'ineuron', 'ineuron02', 'ineuron03')],
          dtype=[(('t', 'f0'), '<U7'), (('h', 'f1'), '<U11'), (('e', 'f2'), '<U11'), (('', 'f3'), '<U11')])

In [147]:
r[0][0] = "stu_id"

In [148]:
r

rec.array([('stu_id', '1', '2', '3'), ('name', 'virat', 'rohit', 'rahul'),
           ('college', 'ineuron', 'ineuron02', 'ineuron03')],
          dtype=[(('t', 'f0'), '<U7'), (('h', 'f1'), '<U11'), (('e', 'f2'), '<U11'), (('', 'f3'), '<U11')])

In [149]:
r[0]

('stu_id', '1', '2', '3')

#### IS vs "==" 

"==" - compares the elements  
"is" - compares the memory location

In [ ]:
lst1 = ["rohit","rohit1","rohit2"]
lst2 = ["rohit","rohit1","rohit2"]
lst1 == lst2

In [ ]:
lst1 = ["rohit","rohit1","rohit2"]
lst2 = ["rohit","rohit1","rohit3"]
lst1 == lst2

In [ ]:
lst1 is lst2

In [ ]:
lst1 = ["rohit","rohit1","rohit2"]
lst2 = lst1

In [ ]:
lst1 == lst2

In [ ]:
lst1 is lst2

In [ ]:
lst1 = ["rohit","rohit1","rohit2"]
lst2 = lst1
lst2[0] = "virat"

In [ ]:
lst1 == lst2

In [ ]:
lst1 is lst2

In [ ]:
# to check the memory loaction

print(id(lst1))
print(id(lst2))

In [ ]:
a = 10
b = 10
print(a is b)
print(a == b)

 ### Data types

In [150]:
lst = [1,2,3]
arr = np.array(lst)
type(arr)

numpy.ndarray

In [152]:
mat1 = [[1,2,3],[4,5,6],[7,8,9]]
mat = np.array(mat1)
mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [155]:
mat.ndim  ## gives the dimension of the array

2

In [157]:
mat.shape  ## gives the shape of the array

(3, 3)

In [158]:
mat.size  ## gives the size of the array

9

## Reshape and Resize difference

Reshape changes the shape of the array with the number of elements being same.  
Resize is used to increase or decrease the number of elemnts in the array.

In [159]:
mat.dtype

dtype('int32')

In [161]:
mat1 = [[1.2,2,3],[4,5.3,6],[7,8,9]]
mat = np.array(mat1)
mat.dtype

dtype('float64')

In [164]:
# tuples used to create array

mat1 = [(1,2,3),(4,5,6),(7,8,9)]
mat = np.array(mat1)
mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### np.arange( ), linspace( ), np.logspace( )

In [166]:
np.arange(5,2,-1)

# np.arange(start,stop,step_size)

array([5, 4, 3])

In [169]:
np.arange(5,10,2)

array([5, 7, 9])

In [170]:
np.arange(5,10,2.5)

array([5. , 7.5])

In [171]:
np.arange(0,20,2).reshape(5,2)

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10],
       [12, 14],
       [16, 18]])

In [174]:
np.linspace(1, 10,10)

# np.linspace(start,stop,number of val b/w start n stop)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [177]:
np.linspace(0, 5,11)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

In [178]:
# get 20 numbers between 0 to 1

np.linspace(0, 1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [212]:
np.linspace(2.0, 3.0, num=5, endpoint=False) # excludes the end point of the range

array([2. , 2.2, 2.4, 2.6, 2.8])

In [213]:
np.linspace(2.0, 3.0, num=11, retstep=True) # it returns the step size

(array([2. , 2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9, 3. ]), 0.1)

In [214]:
#Return numbers spaced evenly on a log scale.
np.linspace(2.0, 3.0, num=4)

array([2.        , 2.33333333, 2.66666667, 3.        ])

In [215]:
np.logspace(2.0, 3.0, num=4,base = 10)

array([ 100.        ,  215.443469  ,  464.15888336, 1000.        ])

In [216]:
np.logspace(2.0, 3.0, num=4, endpoint=False)

array([100.        , 177.827941  , 316.22776602, 562.34132519])

In [217]:
np.logspace(2.0, 3.0, num=4, base=2.0)

array([4.        , 5.0396842 , 6.34960421, 8.        ])

### np.zeros( ), np.ones( ), np.eye( ), np.empty( )

In [182]:
np.zeros(5,dtype = int)

array([0, 0, 0, 0, 0])

In [184]:
np.zeros((3,5),dtype = int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [187]:
np.zeros((3,2,2),dtype = int)

array([[[0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0]]])

In [188]:
np.ones(5,dtype = int)

array([1, 1, 1, 1, 1])

In [189]:
np.ones((3,5),dtype = int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [190]:
np.ones((3,2,2),dtype = int)

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [192]:
5 + np.zeros((2,2),dtype = int)

array([[5, 5],
       [5, 5]])

In [194]:
5 + np.ones((2,2),dtype = int)

array([[6, 6],
       [6, 6]])

In [278]:
np.empty((2,5), dtype=float)

array([[8.97436674e-312, 2.27270197e-322, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000],
       [1.16095484e-028, 5.16665779e-114, 4.25117434e-096,
        9.78750380e+199, 6.97843734e+252]])

In [201]:
np.empty(2, dtype=float)

array([2.05833592e-312, 2.14321575e-312])

In [204]:
np.eye(5,dtype=int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [207]:
np.eye(5,dtype=int, k=1)  # notice diagonal moving up n down with k

array([[0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0]])

In [208]:
np.eye(5,dtype=int, k=-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0]])

### np.diag( ) - to get the diagonal of the matrix

In [235]:
x = np.arange(20)
y = x.reshape(4,5)
y

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [236]:
np.diag(y)

array([ 0,  6, 12, 18])

In [238]:
np.diag(y,1)

array([ 1,  7, 13, 19])

In [258]:
x = np.arange(16)
y = x.reshape(4,4)
y

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [259]:
y.diagonal()

array([ 0,  5, 10, 15])

In [260]:
np.diagonal(y,1)  # return only specified diagonal

array([ 1,  6, 11])

In [263]:
np.diag(y,1)    # returns a diagonal array and even consruct array from diagonal

array([ 1,  6, 11])

In [264]:
np.diag(np.diag(y))   

array([[ 0,  0,  0,  0],
       [ 0,  5,  0,  0],
       [ 0,  0, 10,  0],
       [ 0,  0,  0, 15]])

In [265]:
np.diag([1,5,9])

array([[1, 0, 0],
       [0, 5, 0],
       [0, 0, 9]])

In [244]:
ae = np.arange(16)
aq = ae.reshape(4,4)
aq

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [248]:
np.diag(np.diag(aq))

array([[ 0,  0,  0,  0],
       [ 0,  5,  0,  0],
       [ 0,  0, 10,  0],
       [ 0,  0,  0, 15]])

### np.diagflat( ) 
Takes input of the container. Flattens it, and it is used as diagonal to create a 2D - array

In [249]:
np.diagflat([[1,2,],[3,4]])

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [250]:
np.diagflat([[1,2,],[3,4]],1) # notice the position of the diagonal

array([[0, 1, 0, 0, 0],
       [0, 0, 2, 0, 0],
       [0, 0, 0, 3, 0],
       [0, 0, 0, 0, 4],
       [0, 0, 0, 0, 0]])

In [252]:
np.diagflat([[1,2,],[3,4]],-1) # notice the position of the diagonal

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [268]:
np.diagflat([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])

array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 5, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 6, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 6]])

In [269]:
np.diagflat([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]]).shape

(12, 12)

### np.tri( ), np.tril( ), np.triu( )

In [272]:
np.tri(3,5,1, dtype= int)

array([[1, 1, 0, 0, 0],
       [1, 1, 1, 0, 0],
       [1, 1, 1, 1, 0]])

In [273]:
np.tri(3, dtype= int)

array([[1, 0, 0],
       [1, 1, 0],
       [1, 1, 1]])

In [277]:
np.tri(5,k = 1 ,dtype= int)

array([[1, 1, 0, 0, 0],
       [1, 1, 1, 0, 0],
       [1, 1, 1, 1, 0],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [285]:
np.tril(np.arange(10, 60, 2).reshape(5,5))

array([[10,  0,  0,  0,  0],
       [20, 22,  0,  0,  0],
       [30, 32, 34,  0,  0],
       [40, 42, 44, 46,  0],
       [50, 52, 54, 56, 58]])

In [289]:
np.tril(np.arange(10, 60, 2).reshape(5,5),1)

array([[10, 12,  0,  0,  0],
       [20, 22, 24,  0,  0],
       [30, 32, 34, 36,  0],
       [40, 42, 44, 46, 48],
       [50, 52, 54, 56, 58]])

In [290]:
np.triu(np.arange(10, 60, 2).reshape(5,5))

array([[10, 12, 14, 16, 18],
       [ 0, 22, 24, 26, 28],
       [ 0,  0, 34, 36, 38],
       [ 0,  0,  0, 46, 48],
       [ 0,  0,  0,  0, 58]])

In [291]:
np.triu(np.arange(10, 60, 2).reshape(5,5),1)

array([[ 0, 12, 14, 16, 18],
       [ 0,  0, 24, 26, 28],
       [ 0,  0,  0, 36, 38],
       [ 0,  0,  0,  0, 48],
       [ 0,  0,  0,  0,  0]])

In [313]:
x = (np.arange(10, 60, 2)).reshape(5,5)
il1 = np.tril_indices(5)
il2 = np.tril_indices(4,2)
x

array([[10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28],
       [30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48],
       [50, 52, 54, 56, 58]])

In [314]:
x[il1]

array([10, 20, 22, 30, 32, 34, 40, 42, 44, 46, 50, 52, 54, 56, 58])

In [315]:
x[il2]

array([10, 12, 14, 20, 22, 24, 26, 30, 32, 34, 36, 40, 42, 44, 46])

In [316]:
x = (np.arange(10, 60, 2)).reshape(5,5)
il1 = np.triu_indices(5)
il2 = np.triu_indices(4,2)
x

array([[10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28],
       [30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48],
       [50, 52, 54, 56, 58]])

In [317]:
x[il1]

array([10, 12, 14, 16, 18, 22, 24, 26, 28, 34, 36, 38, 46, 48, 58])

In [318]:
x[il2]

array([14, 16, 26])

### Random number generation

In [322]:
np.random.rand(3,4)   # uniform distribution range(0-1)

array([[0.05621245, 0.41161048, 0.88612265, 0.55123061],
       [0.01694316, 0.09963814, 0.62517594, 0.0692024 ],
       [0.6459681 , 0.72033753, 0.50354283, 0.85537631]])

In [324]:
np.random.randn(3,4)   # standard normal distribution
                       # mean-zero std div-one

array([[-0.0992932 , -0.98232572,  0.22495285, -0.05560434],
       [ 0.30944352, -0.40141995, -0.87655659,  0.11137545],
       [-1.09011756, -0.73173324,  0.17115601,  1.8403189 ]])

In [328]:
np.random.randint(100, 500, 5) 
# takes lower value, higher value, returns the reqired random numbers 
# returns only random integer.

array([477, 411, 474, 359, 224])

In [329]:
np.random.randint(100, 500, (2,2)) 

array([[315, 249],
       [314, 179]])

### Reshaping

In [330]:
a = np.random.randint(1,100,30)
b = np.reshape(a, (2,3,5))
c = np.reshape(a, (5,6))

In [331]:
print(a)
print(b)
print(c)

[67 36 56 76 12 81 94 15 53  3  4 75 61 45 97  9 88 56 98 55  6 97 75 32
 69 35 70 31 43 66]
[[[67 36 56 76 12]
  [81 94 15 53  3]
  [ 4 75 61 45 97]]

 [[ 9 88 56 98 55]
  [ 6 97 75 32 69]
  [35 70 31 43 66]]]
[[67 36 56 76 12 81]
 [94 15 53  3  4 75]
 [61 45 97  9 88 56]
 [98 55  6 97 75 32]
 [69 35 70 31 43 66]]


In [332]:
print(a.shape)
print(b.shape)
print(c.shape)

(30,)
(2, 3, 5)
(5, 6)


In [338]:
np.reshape(a, (5,-25))

array([[67, 36, 56, 76, 12, 81],
       [94, 15, 53,  3,  4, 75],
       [61, 45, 97,  9, 88, 56],
       [98, 55,  6, 97, 75, 32],
       [69, 35, 70, 31, 43, 66]])

### sorting in array

In [340]:
A = np.random.randint(1,100,10)
A

array([85, 82, 69, 75, 90, 77, 86,  2, 81, 80])

In [341]:
np.sort(A)

array([ 2, 69, 75, 77, 80, 81, 82, 85, 86, 90])

In [343]:
A = np.random.randint(1,100,10).reshape(5,2)
A

array([[95, 55],
       [32, 26],
       [36, 37],
       [34, 55],
       [25, 40]])

In [344]:
np.sort(A)

array([[55, 95],
       [26, 32],
       [36, 37],
       [34, 55],
       [25, 40]])

In [347]:
np.sort(A,axis = 0)

array([[25, 26],
       [32, 37],
       [34, 40],
       [36, 55],
       [95, 55]])

### min, max, argmax, argmin

axis = 0 ----- operation along column  
axis = 1 ----- operation along row

In [357]:
print(b)
print("-" *20)
print(c)
print("-" *20)
print(b.max())
print(c.max())
print("-" *20)
print(np.max(b))
print(np.max(c))
print("-" *20)
print(b.min())
print(c.min())
print("-" *20)
print(np.min(b))
print(np.min(c))

[[[67 36 56 76 12]
  [81 94 15 53  3]
  [ 4 75 61 45 97]]

 [[ 9 88 56 98 55]
  [ 6 97 75 32 69]
  [35 70 31 43 66]]]
--------------------
[[67 36 56 76 12 81]
 [94 15 53  3  4 75]
 [61 45 97  9 88 56]
 [98 55  6 97 75 32]
 [69 35 70 31 43 66]]
--------------------
98
98
--------------------
98
98
--------------------
3
3
--------------------
3
3


In [361]:
# gives the index of the flattened array by default
# we can get max and min value from the row n col as well

np.argmax(b)

18

In [360]:
np.argmin(b)

9

In [365]:
np.argmax(c, axis = 0) # index of max elements in the array c

array([3, 3, 2, 3, 2, 0], dtype=int64)

In [366]:
np.argmax(c, axis = 1)

array([5, 0, 2, 0, 2], dtype=int64)

### indexing and slicing

In [368]:
a = np.random.randint(0,100,30).reshape(5,6)
a

array([[77, 56, 84, 23, 67, 24],
       [10,  3,  4, 91, 70, 98],
       [48, 58,  4, 70,  7, 22],
       [45, 93, 38, 68, 87,  3],
       [57, 52, 52, 86, 57, 55]])

In [398]:
a[2:4,2:4]   # range of rows , range of columns

array([[ 4, 70],
       [38, 68]])

In [399]:
a[:, [1,3]]   # selecting 1st and 3rd columns

array([[56, 23],
       [ 3, 91],
       [58, 70],
       [93, 68],
       [52, 86]])

In [403]:
a[[1,3],:][:,[1,3]]

array([[ 3, 91],
       [93, 68]])

In [404]:
a[1]   # index 1 row

array([10,  3,  4, 91, 70, 98])

In [420]:
a[1,1]  # value at index[1,1]

3

In [421]:
a[1][1]  # similar to above case

3

In [416]:
a[:,2:]   #all rows, all columns from 2nd index

array([[84, 23, 67, 24],
       [ 4, 91, 70, 98],
       [ 4, 70,  7, 22],
       [38, 68, 87,  3],
       [52, 86, 57, 55]])

In [417]:
a[:,2]   # all rows, only 2nd column

array([84,  4,  4, 38, 52])

### Issue in slicing

In [423]:
mat = np.array([[11,12,13],[21,22,23],[31,32,33]])
mat    # defining and printing mat 

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [425]:
sliced_mat = mat[:2,:2]
sliced_mat    # slicing mat to get sliced_mat

array([[11, 12],
       [21, 22]])

In [430]:
sliced_mat[0,0] = 101
sliced_mat    # changing values of sliced_mat and viewing it

array([[101,  12],
       [ 21,  22]])

In [431]:
mat   # viewing mat

array([[101,  12,  13],
       [ 21,  22,  23],
       [ 31,  32,  33]])

In [441]:
# oh crap!, even mat changed along with sliced_mat.
# see below how to avoid it

# please note the changes done while savinf sliced_mat.
#its an important thing to remember as we can make a big damage to data if we dont follow it.

In [437]:
mat1 = np.array([[11,12,13],[21,22,23],[31,32,33]])
mat1    # defining and printing mat 

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [438]:
sliced_mat1 = np.array(mat1[:2,:2])
sliced_mat1    # slicing mat to get sliced_mat

array([[11, 12],
       [21, 22]])

In [439]:
sliced_mat1[0,0] = 101
sliced_mat1    # changing values of sliced_mat and viewing it

array([[101,  12],
       [ 21,  22]])

In [440]:
mat1   # viewing mat

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

### subsetting

In [442]:
mat1

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [444]:
mat1>22   # checks value greater than 22, returns bool output

array([[False, False, False],
       [False, False,  True],
       [ True,  True,  True]])

In [447]:
mat[mat1>22] # returns the list of values where comparision is true

array([23, 31, 32, 33])

### universal functions

In [450]:
mat1 = np.random.randint(1,10,9).reshape(3,3)
mat1

array([[1, 2, 8],
       [9, 6, 3],
       [5, 5, 5]])

In [451]:
mat2 = np.random.randint(1,10,9).reshape(3,3)
mat2

array([[8, 9, 2],
       [8, 7, 3],
       [8, 1, 4]])

In [452]:
# element wise multiplication

mat1 * mat2

array([[ 8, 18, 16],
       [72, 42,  9],
       [40,  5, 20]])

In [453]:
# matrix multiplication

mat1 @ mat2

array([[ 88,  31,  40],
       [144, 126,  48],
       [120,  85,  45]])

In [454]:
mat1 / 0

C:\Users\User\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [455]:
100 + mat1

array([[101, 102, 108],
       [109, 106, 103],
       [105, 105, 105]])

In [457]:
mat1**3

array([[  1,   8, 512],
       [729, 216,  27],
       [125, 125, 125]], dtype=int32)

In [458]:
pow(mat1,3)

array([[  1,   8, 512],
       [729, 216,  27],
       [125, 125, 125]], dtype=int32)

### Broadcasting

In [462]:
a = np.random.randint(0,100,30).reshape(6,5)
a

array([[53, 33, 83, 70, 53],
       [98, 58, 31, 64, 52],
       [68, 12, 44,  7,  4],
       [10, 92, 19, 42, 39],
       [64,  0, 23, 63, 23],
       [50, 44, 99, 84,  4]])

In [464]:
a[3:] = 100

In [465]:
a

array([[ 53,  33,  83,  70,  53],
       [ 98,  58,  31,  64,  52],
       [ 68,  12,  44,   7,   4],
       [100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100]])

In [466]:
start = np.zeros((4,4))
start= start+100
start

array([[100., 100., 100., 100.],
       [100., 100., 100., 100.],
       [100., 100., 100., 100.],
       [100., 100., 100., 100.]])

In [467]:
# create a rank 1 ndarray with 3 values
add_rows = np.array([1, 0, 2,5])
print(add_rows)

[1 0 2 5]


In [468]:
y = start + add_rows  # add to each row of 'start' using broadcasting
print(y)

[[101. 100. 102. 105.]
 [101. 100. 102. 105.]
 [101. 100. 102. 105.]
 [101. 100. 102. 105.]]


In [469]:
# create an ndarray which is 4 x 1 to broadcast across columns
add_cols = np.array([[0,1,2,3]])
add_cols = add_cols.T
print(add_cols)

[[0]
 [1]
 [2]
 [3]]


In [470]:
# add to each column of 'start' using broadcasting
y = start + add_cols 
print(y)

[[100. 100. 100. 100.]
 [101. 101. 101. 101.]
 [102. 102. 102. 102.]
 [103. 103. 103. 103.]]


In [476]:
# this will just broadcast in both dimensions
add_scalar = np.array([100])  
print(y+add_scalar)

[[200. 200. 200. 200.]
 [201. 201. 201. 201.]
 [202. 202. 202. 202.]
 [203. 203. 203. 203.]]


### numpy math

In [477]:
mat1

array([[1, 2, 8],
       [9, 6, 3],
       [5, 5, 5]])

In [478]:
mat2

array([[8, 9, 2],
       [8, 7, 3],
       [8, 1, 4]])

In [479]:
np.sqrt(mat1)

array([[1.        , 1.41421356, 2.82842712],
       [3.        , 2.44948974, 1.73205081],
       [2.23606798, 2.23606798, 2.23606798]])

In [480]:
np.exp(mat1)

array([[2.71828183e+00, 7.38905610e+00, 2.98095799e+03],
       [8.10308393e+03, 4.03428793e+02, 2.00855369e+01],
       [1.48413159e+02, 1.48413159e+02, 1.48413159e+02]])

In [481]:
np.power(mat1,2)

array([[ 1,  4, 64],
       [81, 36,  9],
       [25, 25, 25]], dtype=int32)

In [482]:
np.log10(mat1)

array([[0.        , 0.30103   , 0.90308999],
       [0.95424251, 0.77815125, 0.47712125],
       [0.69897   , 0.69897   , 0.69897   ]])

In [484]:
np.fmod(mat2,mat1)

array([[0, 1, 2],
       [8, 1, 0],
       [3, 1, 4]], dtype=int32)

In [485]:
mat2%mat1

array([[0, 1, 2],
       [8, 1, 0],
       [3, 1, 4]], dtype=int32)

In [489]:
np.round((np.pi*mat1),2)

array([[ 3.14,  6.28, 25.13],
       [28.27, 18.85,  9.42],
       [15.71, 15.71, 15.71]])

In [493]:
np.pi

3.141592653589793

In [494]:
np.greater(mat1,mat2)

array([[False, False,  True],
       [ True, False, False],
       [False,  True,  True]])

# The above discussed are only some important concepts. For all methods and information about Numpy visit.

https://numpy.org/doc/stable/reference/ufuncs.html